name: Playwright Tests (Web Deploy Only)

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout pruebas Playwright
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Instalar dependencias de pruebas
        run: npm ci

      - name: Instalar navegadores Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar pruebas contra entorno desplegado
        run: npx playwright test --project="Web Angular (Producción)"

      - name: Subir reporte HTML
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30